apiVersion: v1
kind: Pod
metadata:
  name: golang-pod
spec:
  containers:
    - name: test-container
      image: laotacluong/golang-app:3.0
      command: [ "/bin/sh","-c","go run main.go" ]
      volumeMounts:
      - name: config-volume
        mountPath: /go/src/app/static/volume
  volumes:
    - name: config-volume
      configMap:
        name: special-config
        items:
        - key: config.properties
          path: configmap.conf

