apiVersion: v1
kind: Pod
metadata:
  name: golang-pod
spec:
  containers:
    - name: test-container
      image: laotacluong/golang-app:v1
      volumeMounts:
      - name: config-volume
        mountPath: /config
  volumes:
    - name: config-volume
      configMap:
        name: special-config
        items:
        - key: config.properties
          path: config.conf
  restartPolicy: Never
