apiVersion: v1
kind: Pod
metadata:
  name: golang-pod
spec:
  containers:
    - name: test-container
      image: laotacluong/golang-app:2.0
      volumeMounts:
      - name: config-volume
        mountPath: /static
  volumes:
    - name: config-volume
      configMap:
        name: special-config
        items:
        - key: config.properties
          path: config.conf

